FROM codercom/code-server:fedora

RUN sudo dnf update -y \
  && sudo dnf install -y fira-code-fonts java-latest-openjdk.x86_64 nodejs 

RUN sudo npm install -g pnpm \
  && sudo npm install -g aicommit2 \
  && sudo aicommit2 config set locale="fr" \
  && sudo aicommit2 config set type="gitmoji" \
  && sudo aicommit2 config set includeBody="true" \
  && sudo aicommit2 config set OLLAMA.host=project-ollama \
  && sudo aicommit2 config set OLLAMA.model=<your model> \
  && sudo aicommit2 config set OLLAMA.numCtx=4096

WORKDIR /home/coder/project