FROM node:lts AS build
WORKDIR /app

ARG API_BASE_URL 
ARG APP_DOMAIN 
ARG APP_NAME 
ARG APP_URL 
ARG APP_ENVIRONMENT
ARG COMPATIBILITY_DATE
ARG NUXT_RESEND_API_KEY
ARG SENTRY_DSN
ARG SENTRY_AUTH_TOKEN

ENV npm_config_platform=linux
ENV npm_config_libc=glibc
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="/root/.local/share/pnpm:$PATH"

RUN apt-get update && apt-get install -y --no-install-recommends \
  python3 \
  build-essential \
  libvips-dev \
  && rm -rf /var/lib/apt/lists/*

RUN npm install --quiet node-gyp -g && \
    npm install -g pnpm@latest

COPY package.json pnpm-lock.yaml pnpm.json pnpm-workspace.yaml ./

RUN  pnpm install && \
  pnpm install vue
# pnpm config set store-dir /root/.local/share/pnpm/store --global && \

COPY . .

ENV PATH="./node_modules/.bin/:$PATH"

RUN pnpm run build

FROM node:lts-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  libvips \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN echo ${SENTRY_AUTH_TOKEN} > .env.sentry-build-plugin && \
  chmod 600 .env.sentry-build-plugin

COPY --from=build /app/.output /app/.output
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json /app/pnpm-lock.yaml /app/

EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]