// vuetify.config.ts
import { defineVuetifyConfiguration } from 'vuetify-nuxt-module/custom-configuration'

const chartman2frLightTheme = {
  dark: false,
  colors: {
    'primary': '#00658e',
    'secondary': '#bd4500',
    'info': '#006a63',
    'error': '#b50079',
    'warning': '#a53b12',
    'success': '#006e21',
    'background': '#c7e7ff',
    'surface': '#F5F5F5',
    'muted': '#566670',
    'border': '#d4dce2',
    'article-card': '#F5F5F5',
    'on-primary': '#ffffff',
    'on-secondary': '#ffffff',
    'on-info': '#ffffff',
    'on-error': '#ffffff',
    'on-warning': '#ffffff',
    'on-success': '#ffffff',
    'on-background': '#1b1c18',
    'primary-container': '#c7e7ff',
    'secondary-container': '#ffdbc7',
    'info-container': '#66f9ea',
    'error-container': '#ffd8e7',
    'success-container': '#89fb8d',
    'warning-container': '#ffdbd0',
    'on-primary-container': '#001e2e',
    'on-secondary-container': '#2e1100',
    'on-info-container': '#00201d',
    'on-error-container': '#3d0026',
    'on-success-container': '#002105',
    'on-warning-container': '#390c00',
  },
}

const chartman2frDarkTheme = {
  dark: true,
  colors: {
    'primary': '#85cfff',
    'secondary': '#ff781b',
    'info': '#41dcce',
    'error': '#ffafd3',
    'warning': '#ffb59c',
    'success': '#6dde73',
    'background': '#001f25',
    'surface': '#234751',
    'code': '#303030',
    'muted': '#91a8b8',
    'border': '#243541',
    'article-card': '#172728',
    'on-primary': '#00344c',
    'on-secondary': '#1b1c18',
    'on-info': '#003733',
    'on-error': '#620040',
    'on-success': '#00390d',
    'on-warning': '#5c1900',
    'on-background': '#a6eeff',
    'primary-container': '#004c6c',
    'secondary-container': '#6c2c00',
    'info-container': '#00504a',
    'error-container': '#8b005c',
    'success-container': '#005316',
    'warning-container': '#832700',
    'on-primary-container': '#c7e7ff',
    'on-secondary-container': '#ffdec7',
    'on-info-container': '#66f9ea',
    'on-error-container': '#ffd8e7',
    'on-success-container': '#89fb8d',
    'on-warning-container': '#ffdbd0',
  },
}

export default defineVuetifyConfiguration({
  icons: {
    defaultSet: 'unocss-mdi',
  },
  theme: {
    defaultTheme: 'chartman2frLightTheme',
    themes: {
      chartman2frLightTheme,
      chartman2frDarkTheme,
    },
  },
})
